### ISSUE TITLE
0.6 "roadmap"

### ISSUE THREAD

**Issue by NieDzejkob** [NieDzejkob/enumflags2#8]
aka "things I want to do before releasing 0.6":

- [x] Merge all PRs, obviously.
- [x] Move the RawBitFlags trait to `_internals`.
- [x] Reexport the proc-macro from the main crate.
  -  [x] Update documentation to discourage direct dependencies on on `enumflags2_derive`.
    - Is there a way to warn about this? Perhaps put `internal` in the macro name and then remove it when reexporting? `#[deprecated]` and `#[allow(deprecated)]` when reexporting? (does that even work?)
  -  [x] Update examples.
 - [x] Implement `TryFrom` as outlined below

**Comment by NieDzejkob** [comment]
> A suggestion/question, since the minimum rustc version is being bumped with this release: any interest in implementing the `TryFrom` fallible conversion traits?

I'm not sure what you're suggesting here? `TryFrom<repr_int>`? `TryFrom<BitFlags<T>> for T`?

**Comment by NieDzejkob** [comment]
> Seems overkill maybe but you could always deprecate the proc-macro crate and release the new one under a different name.

Actually, the crates.io name and the source code name don't have to be the same. The phenomenon is most commonly seen with hyphens vs underscores, but it's not limited to that.

This could be an opportunity/excuse to drop the `2` in `enumflags2` from everywhere but crates.io (and users' Cargo.tomls).



> > Is there a way to warn about this? Perhaps put internal in the macro name and then remove it when reexporting?
> 
> Hm not actually sure, can you rename with `#[macro_export()]`? `pub use macro as something;` doesn't even work in 2018 (yet?) :(

It seems to work in 2015, though. See the [`reexport-derive-internal-in-name`](https://github.com/NieDzejkob/enumflags2/tree/reexport-derive-internal-in-name) branch.

**Comment by NieDzejkob** [comment]
> > This could be an opportunity/excuse to drop the 2 in enumflags2 from everywhere but crates.io (and users' Cargo.tomls).
> 
> Ooh yeah that would be nice.

What do you think about naming the macro itself `BitFlags`? I might do these two changes, but I'm not quite sure about the potential cons here.

**Comment by NieDzejkob** [comment]
On Wed, Aug 28, 2019 at 09:00:16AM -0700, arcnmx wrote:
> Also regarding `TryFrom`, [I tried and failed](https://github.com/arcnmx/enumflags2/commit/fallible).

I am currently implementing a workaround with a declarative macro.
